[tool.poetry]
name = "fantasion-backend"
version = "0.1.0"
description = ""
authors = ["Pavel Žák <pavel@zak.global>"]

[tool.poetry.dependencies]
python = "^3.9"
Django = "^3.2.9"
django-extensions = "^3.1.5"
django-modeltranslation = "^0.17.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
