# Generated by Django 4.2.27 on 2025-12-31 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fantasion_eshop", "0029_alter_order_price_alter_productprice_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="reference_number",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Reference Number"
            ),
        ),
    ]
