---
name: Integration
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - 'v*'

jobs:
  build-backend:
    name: Test and build backend
    runs-on: ubuntu-latest
    env:
      wd: ./packages/fantasion-backend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.1
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.12
      - name: Install dependencies
        working-directory: ${{env.wd}}
        run: poetry install
      - name: Check coding style
        working-directory: ${{env.wd}}
        run: poetry run flake8
      - name: Run tests
        working-directory: ${{env.wd}}
        run: poetry run ./manage.py test
