---
name: Integration
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'

jobs:
  test-and-build:
    name: Test and build
    runs-on: ubuntu-latest
    env:
      dir_backend: ./packages/fantasion-backend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.1
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.12
      - uses: actions/cache@v1
        with:
          path: |
            ~/.npm
            ~/.cache/pypoetry
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        run: npm ci
      - name: Check coding style
        working-directory: ${{env.dir_backend}}
        run: poetry run flake8
      - name: Run backend tests
        working-directory: ${{env.dir_backend}}
        run: poetry run ./manage.py test
      - name: Run frontend tests
        run: npm run test -- --coverage
      - name: Build all packages
        run: NODE_ENV=production npm run build
      - name: Store artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            packages/fantasion-backend/dist/
            packages/fantasion-web/.next
