---
name: Release
on:
  workflow_dispatch:
    branches:
      - master

jobs:
  tag_version:
    name: Tag version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - uses: plutotcool/release@v2.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish: false
